PAWaves/urls.py
from django.contrib import admin
from django.urls import path,include
from plotter import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plotter.urls')),
]

plotter/urls.py
from django.urls import path
from . import views

# Define the URL patterns for the plotter app
urlpatterns = [
    # Map the root URL (e.g., /plotter/) to the plot_view function
    path('', views.plot_view, name='plot_view'),
]

plotter/models.py
from django.db import models

# Create your models here.

plotter/forms.py
from django import forms

class MultiplierForm(forms.Form):
    ibias = forms.FloatField(label='ibias', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    i1 = forms.FloatField(label='i1', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    i2 = forms.FloatField(label='i2', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    i3 = forms.FloatField(label='i3', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    i4 = forms.FloatField(label='i4', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    i5 = forms.FloatField(label='i5', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    i6 = forms.FloatField(label='i6', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    i7 = forms.FloatField(label='i7', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))


    vknee = forms.FloatField(label='vknee', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    vdc = forms.FloatField(label='vdc', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    vmin = forms.CharField(label='vmin', required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))

    mag_v1 = forms.FloatField(label='mag_v1', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    mag_v2 = forms.FloatField(label='mag_v2', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    mag_v3 = forms.FloatField(label='mag_v3', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    mag_v4 = forms.FloatField(label='mag_v4', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    mag_v5 = forms.FloatField(label='mag_v5', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    mag_v6 = forms.FloatField(label='mag_v6', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    mag_v7 = forms.FloatField(label='mag_v7', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))

    ang_v1 = forms.FloatField(label='ang_v1', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    ang_v2 = forms.FloatField(label='ang_v2', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    ang_v3 = forms.FloatField(label='ang_v3', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    ang_v4 = forms.FloatField(label='ang_v4', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    ang_v5 = forms.FloatField(label='ang_v5', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    ang_v6 = forms.FloatField(label='ang_v6', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))
    ang_v7 = forms.FloatField(label='ang_v7', required=False, widget=forms.NumberInput(attrs={'step': 'any', 'class': 'form-control'}))

    output_format = forms.ChoiceField(choices=[('svg', 'SVG'),('png', 'PNG')], label='Graph Save Format', widget=forms.Select(attrs={'class': 'form-select'}), initial='svg')
    preset = forms.ChoiceField(choices=[('A', 'Class A'), ('AB', 'Class AB'),('B', 'Class B'),('C', 'Class C'), ('F', 'Class F'), ('custom', 'Custom')], label='Graph Save Format', widget=forms.Select(attrs={'class': 'form-select'}), initial='A')

plotter/views.py
from django.shortcuts import render
from .forms import MultiplierForm
import matplotlib.pyplot as plt
import numpy as np
import io
import urllib, base64
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.backends.backend_svg import FigureCanvasSVG
from .calculations import calculate_output 
from pathlib import Path
from django.conf import settings
import csv
from matplotlib.ticker import FormatStrFormatter, MultipleLocator


def plot_view(request):
    plot_url = None
    import json

    json_file_path = Path(settings.STATIC_ROOT) / 'presets' / 'class_presets.json'

    # Load the JSON data
    with open(json_file_path, 'r') as f:
        preset_values = json.load(f)


    if request.method == 'POST':
        form = MultiplierForm(request.POST)
        if form.is_valid():
            preset = form.cleaned_data.get('preset')
            output_format = form.cleaned_data.get('output_format', 'svg')

            if preset != 'custom':
                output_values = calculate_output(preset_values[preset])
            else:
                output_values = calculate_output(form.cleaned_data)

    else:
        # On GET request or initial load, apply the Class A preset
        form = MultiplierForm(initial=preset_values['A'])
        # output_values = calculate_output(preset_values['A'])
        output_values = calculate_output(preset_values['A'])
        output_format = 'svg'
    


    # Generate the plot based on output_values
    if output_values.get('voltage_wfm'):
        x = output_values['angles_wfm']
        y = output_values['voltage_wfm']

        fig, ax = plt.subplots(figsize=(10, 6))
        ax.plot(output_values['current_angles_wfm'],output_values['zeroknee'], label="Zeroknee",linewidth=1.8)
        ax.plot(x, y, label="Voltage", linewidth=1.8)
        ax.plot(output_values['current_angles_wfm'],output_values['current_wfm'], label="Current",linewidth=1.8)
        ax.set_ylim([0, None])
        ax.set_xlim([min(output_values['angles_wfm'][0], output_values['current_angles_wfm'][0]),
                    max(output_values['angles_wfm'][-1], output_values['current_angles_wfm'][-1])])
        ax.legend()
        ax.xaxis.set_major_locator(plt.MultipleLocator(np.pi / 2))
        ax.xaxis.set_minor_locator(plt.MultipleLocator(np.pi / 12))
        ax.xaxis.set_major_formatter(plt.FuncFormatter(multiple_formatter()))
        ax.grid()
        plt.xticks(fontsize=16)
        plt.yticks(fontsize=14)

        buf = io.BytesIO()
        if output_format == 'png':
            canvas = FigureCanvas(fig)
            canvas.print_png(buf)
            content_type = 'image/png'
        else:
            canvas = FigureCanvasSVG(fig)
            canvas.print_svg(buf)
            content_type = 'image/svg+xml'

        buf.seek(0)
        string = base64.b64encode(buf.read()).decode()
        plot_url = f"data:{content_type};base64,{string}"
        plt.close(fig)

        
        # Create a CSV file in memory
        csv_output = io.StringIO()
        writer = csv.writer(csv_output)

        # Write the header
        writer.writerow(['X(Angle)','Y(Voltage)', 'Y(Current)', 'Y(Zeroknee)'])

        # Write the data rows
        for angle, voltage, current, zeroknee in zip(output_values['current_angles_wfm'],output_values['voltage_wfm'], output_values['current_wfm'], output_values['zeroknee']):
            writer.writerow([angle, voltage, current, zeroknee])

        csv_output.seek(0)  # Rewind the CSV file to the beginning

        # Create a downloadable link for the CSV file
        csv_download_url = f"data:text/csv;base64,{base64.b64encode(csv_output.getvalue().encode()).decode()}"


    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return render(request, 'plotter/plot.html', {
            'form': form,
            'plot_url': plot_url,
            'output_format': output_format,
            'output_values': output_values,
            'csv_download_url': csv_download_url
        })

    return render(request, 'plotter/plot.html', {
        'form': form,
        'plot_url': plot_url,
        'output_format': output_format,
        'output_values': output_values,
        'csv_download_url': csv_download_url
    })


def multiple_formatter(denominator=2, number=np.pi, latex='\pi'):
    def gcd(a, b):
        while b:
            a, b = b, a%b
        return a
    def _multiple_formatter(x, pos):
        den = denominator
        num = int(np.rint(den*x/number))
        com = gcd(num,den)
        (num,den) = (int(num/com),int(den/com))
        if den==1:
            if num==0:
                return r'$0$'
            if num==1:
                return r'$%s$'%latex
            elif num==-1:
                return r'$-%s$'%latex
            else:
                return r'$%s%s$'%(num,latex)
        else:
            if num==1:
                return r'$\frac{%s}{%s}$'%(latex,den)
            elif num==-1:
                return r'$\frac{-%s}{%s}$'%(latex,den)
            else:
                return r'$\frac{%s%s}{%s}$'%(num,latex,den)
    return _multiple_formatter

plotter/templates/plotter/plot.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APAC</title>
    <link rel="stylesheet" href="{% static 'css/plotter.css' %}">
    <script src="{% static 'js/plotter.js' %}"></script>
    <script async="" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML" type="text/javascript"></script>
</head>

<body>
    <h1>\[\text{Analytical Power Amplifier Calculator - APAC}\]</h1>
    <!-- Form Container -->
    <form id="plotForm" method="post">
        {% csrf_token %}
        <div class="container">
            <div class="column large">
                <div class="section large">
                    <div class="row">
                        <div></div>
                        <label for="input8">\[I_1\]</label>
                        <label for="input9">\[I_2\]</label>
                        <label for="input10">\[I_3\]</label>
                        <label for="input11">\[I_4\]</label>
                        <label for="input12">\[I_5\]</label>
                        <label for="input13">\[I_6\]</label>
                        <label for="input14">\[I_7\]</label>
                    </div>
                    <div class="row">
                        <label for="input8">\[Mag\]</label>
                        {{ form.i1 }}
                        {{ form.i2 }}
                        {{ form.i3 }}
                        {{ form.i4 }}
                        {{ form.i5 }}
                        {{ form.i6 }}
                        {{ form.i7 }}
                    </div>
                    <div class="row">
                        <div></div>
                        <label for="input15">\[V_1\]</label>
                        <label for="input16">\[V_2\]</label>
                        <label for="input17">\[V_3\]</label>
                        <label for="input18">\[V_4\]</label>
                        <label for="input19">\[V_5\]</label>
                        <label for="input20">\[V_6\]</label>
                        <label for="input21">\[V_7\]</label>
                    </div>
                    <div class="row">
                        <label for="input22">\[Mag\]</label>
                        {{ form.mag_v1 }}
                        {{ form.mag_v2 }}
                        {{ form.mag_v3 }}
                        {{ form.mag_v4 }}
                        {{ form.mag_v5 }}
                        {{ form.mag_v6 }}
                        {{ form.mag_v7 }}
                    </div>
                    <div class="row">
                        <label for="input23">\[Angle\]</label>
                        {{ form.ang_v1 }}
                        {{ form.ang_v2 }}
                        {{ form.ang_v3 }}
                        {{ form.ang_v4 }}
                        {{ form.ang_v5 }}
                        {{ form.ang_v6 }}
                        {{ form.ang_v7 }}
                    </div>
                    <div class="row">
                        <label for="input24">\[\mathfrak{Re}\{V_i\}\]</label>
                        <div class="readonly-field re_v1">{{ output_values.re_v1 }}</div>
                        <div class="readonly-field re_v2">{{ output_values.re_v2 }}</div>
                        <div class="readonly-field re_v3">{{ output_values.re_v3 }}</div>
                        <div class="readonly-field re_v4">{{ output_values.re_v4 }}</div>
                        <div class="readonly-field re_v5">{{ output_values.re_v5 }}</div>
                        <div class="readonly-field re_v6">{{ output_values.re_v6 }}</div>
                        <div class="readonly-field re_v7">{{ output_values.re_v7 }}</div>
                    </div>
                    <div class="row">
                        <label for="input25">\[\mathfrak{Im}\{V_i\}\]</label>
                        <div class="readonly-field im_v1">{{ output_values.im_v1 }}</div>
                        <div class="readonly-field im_v2">{{ output_values.im_v2 }}</div>
                        <div class="readonly-field im_v3">{{ output_values.im_v3 }}</div>
                        <div class="readonly-field im_v4">{{ output_values.im_v4 }}</div>
                        <div class="readonly-field im_v5">{{ output_values.im_v5 }}</div>
                        <div class="readonly-field im_v6">{{ output_values.im_v6 }}</div>
                        <div class="readonly-field im_v7">{{ output_values.im_v7 }}</div>
                    </div>
                </div>
            </div>
            
            <div class="section tall">
                <div class="row">
                    <label for="input26">\[I_{bias}\]</label>
                    {{ form.ibias }}
                </div>
                <div class="row">
                    <label for="input27">\[V_{knee}\]</label>
                    {{ form.vknee }}
                </div>
                <div class="row">
                    <label for="input28">\[V_{DC}\]</label>
                    {{ form.vdc }}
                </div>
                <div class="row">
                    <label for="input29">\[V_{min}\]</label>
                    <div class="readonly-field vmin">{{ output_values.vmin }}</div>
                </div>
                </div>
            
            <div class="section full-span">
                <div class="row">
                    <label for="input30">\[P_{out}\;[dB]\]</label>
                    <div class="readonly-field pout">{{ output_values.pout }}</div>
                    <label for="input31">\[\eta\;[\%]\]</label>
                    <div class="readonly-field eta">{{ output_values.eta }}</div>
                </div>
            </div>
        </div>

        <div id="plot-container" class="graph1">
            {% if plot_url %}
                <!-- Add an ID to the img tag for easier selection in JavaScript -->
                <img id="generated-plot" src="{{ plot_url }}" alt="Generated Plot"/>
            {% else %}
                <p class="text-muted">No plot available. Please enter a multiplier to see the plot.</p>
            {% endif %}
        </div>
        
        <div id="plot-config" class="plotconfig">
            <div class="dropdown-container">
                <label for="id_preset">Select Preset:</label>
                {{ form.preset }}
            </div>
        
            <div class="dropdown-container">
                <label for="format-select">Output Format:</label>
                {{ form.output_format }}
            </div>
            <div class="download-buttons">
                {% if plot_url %}
                    <a id="save-graph-link" href="{{ plot_url }}" download="plot_wfm" class="button">
                        Save Graph
                    </a>
                {% endif %}
                
                {% if csv_download_url %}
                    <a id="download-csv-link" href="{{ csv_download_url }}" download="data_wfm.csv" class="button">
                        Download CSV
                    </a>
                {% endif %}
            </div>
        </div>
        
    </form>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>